// vite.config.ts
import { defineConfig } from "vite";
import * as builtins from "builtin-modules";

// Banner identical to your esbuild setup
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

// External modules (Obsidian plugin + Node built-ins + CodeMirror/Lezer)
const externals = [
	"obsidian",
	"electron",
	"@codemirror/autocomplete",
	"@codemirror/collab",
	"@codemirror/commands",
	"@codemirror/language",
	"@codemirror/lint",
	"@codemirror/search",
	"@codemirror/state",
	"@codemirror/view",
	"@lezer/common",
	"@lezer/highlight",
	"@lezer/lr",
	...builtins,
];

export default defineConfig(({ mode }) => {
	const prod = mode === "production";

	return {
		build: {
			// Lib mode to control format/file name
			lib: {
				entry: "src/main.ts",
				formats: ["cjs"],
				fileName: () => "main",
			},
			target: "es2018",
			sourcemap: prod ? false : "inline",
			minify: prod, // Vite defaults to minify in prod, but we mirror your flag
			outDir: ".", // Obsidian expects main.js at project root
			emptyOutDir: false, // don't wipe manifest/readme, etc.
			rollupOptions: {
				external: externals,
				output: {
					// Ensure the file is exactly main.js and add the banner
					entryFileNames: "main.js",
					banner,
					// Keep CJS semantics tidy (usually not required, but harmless)
					exports: "auto",
				},
				// Optional: keep entry signature minimal (helps some CJS consumers)
				// preserveEntrySignatures: "exports-only",
			},
		},
		// Keep logs fairly similar to esbuild's "info"
		logLevel: "info",
		// Tree-shaking is on by default in Rollup/Vite
		// esbuild options used during TS/JS transform (not final bundling)
		esbuild: {
			legalComments: "none",
		},
	};
});
